#!/usr/bin/python

import os
import sys
if sys.argv[1:] == ["config"]:
	print "graph_title Raw ADC readings"
	print "graph_vlabel value"
	print "graph_category Solar"
	for i in range(4):
		print "a%d.label A%d" % (i, i)
	exit()

# Import the ADS1x15 module. Install with sudo pip install
import Adafruit_ADS1x15

# Create an ADS1115 ADC (16-bit) instance.
adc = Adafruit_ADS1x15.ADS1115()

# See table 3 in the ADS1015/ADS1115 datasheet for more info on gain.
GAIN = 1

for i in range(4):
        value = adc.read_adc(i, gain=GAIN)
	print "a%d.value" % i, value
