#!/usr/bin/python
# coding: latin1

import os
import sys
if sys.argv[1:] == ["config"]:
	print "graph_title Temperature"
	print "graph_vlabel °C"
	print "graph_category Solar"
	print "attic.label Attic"
	exit()

# Import the ADS1x15 module. Install with sudo pip install
import Adafruit_ADS1x15

# Create an ADS1115 ADC (16-bit) instance.
adc = Adafruit_ADS1x15.ADS1115()

# See table 3 in the ADS1015/ADS1115 datasheet for more info on gain.
GAIN = 1

value = sum(adc.read_adc(0, gain=GAIN) for i in range(50)) / 50.0
print "attic.value", 16 + (22 - 16) * (value - 8530.0) / (9705 - 8530)
